CREATE TABLE [dbo].[FormI9ChangeSet] (
    [FormI9ChangeSetID]     INT           IDENTITY (1, 1) NOT NULL,
    [FormI9ID]              INT           NOT NULL,
    [EmployeeID]            INT           NOT NULL,
    [FirstName]             VARCHAR (50)  NOT NULL,
    [MiddleName]            VARCHAR (50)  NULL,
    [LastName]              VARCHAR (50)  NOT NULL,
    [StartDate]             DATE          NULL,
    [EndDate]               DATE          NULL,
    [Address1]              VARCHAR (100) NOT NULL,
    [Address2]              VARCHAR (100) NULL,
    [City]                  VARCHAR (50)  NOT NULL,
    [State]                 VARCHAR (50)  NOT NULL,
    [Country]               VARCHAR (50)  NOT NULL,
    [ZipCode]               VARCHAR (10)  NOT NULL,
    [BirthDate]             DATE          NOT NULL,
    [SSN]                   VARCHAR (9)   NOT NULL,
    [Phone]                 VARCHAR (10)  NOT NULL,
    [Email]                 VARCHAR (50)  NOT NULL,
    [WorkAuthorizationID]   INT           NOT NULL,
    [ANumber]               VARCHAR (10)  NULL,
    [USCISNumber]           VARCHAR (10)  NULL,
    [I94Number]             VARCHAR (11)  NULL,
    [I94ExpiryDate]         DATE          NULL,
    [PassportNumber]        VARCHAR (20)  NULL,
    [PassportCountry]       VARCHAR (50)  NULL,
    [HireDate]              DATE          NOT NULL,
    [ListADocumentTitleID]  INT           NULL,
    [ListAIssuingAuthority] VARCHAR (50)  NULL,
    [ListADocumentNumber]   VARCHAR (50)  NULL,
    [ListAStartDate]        DATE          NULL,
    [ListAExpirationDate]   DATE          NULL,
    [ListBDocumentTitleID]  INT           NULL,
    [ListBIssuingAuthority] VARCHAR (50)  NULL,
    [ListBDocumentNumber]   VARCHAR (50)  NULL,
    [ListBStartDate]        DATE          NULL,
    [ListBExpirationDate]   DATE          NULL,
    [ListCDocumentTitleID]  INT           NULL,
    [ListCIssuingAuthority] VARCHAR (50)  NULL,
    [ListCDocumentNumber]   VARCHAR (50)  NULL,
    [ListCStartDate]        DATE          NULL,
    [ListCExpirationDate]   DATE          NULL,
    [IsDeleted]             BIT           NOT NULL,
    [CreatedBy]             VARCHAR (50)  NOT NULL,
    [CreatedDate]           DATETIME      NOT NULL,
    [ModifiedBy]            VARCHAR (50)  NULL,
    [ModifiedDate]          DATETIME      NULL,
    [TimeStamp]             ROWVERSION    NOT NULL
);

