export class ICompanyDisplay {
    companyID: number;
    name: string;
    address1: string;
    address2: string;
    city: string;
    state: string;
    country: string;
    zipCode: string;
    contactName: string;
    contactEmail: string;
    contactPhone: string;
    alternateContactName: string;
    alternateContactEmail: string;
    alternateContactPhone: string;
    invoiceContactName: string;
    invoiceContactEmail: string;
    invoiceContactPhone: string;
    alternateInvoiceContactName: string;
    alternateInvoiceContactEmail: string;
    alternateInvoiceContactPhone: string;
    invoicingPeriodID: number;
    invoicingPeriod: string
    paymentTermID: number;
    paymentTerm?: string;
    taxID: number;
    companyTypeID?: number;
    companyType: string;
    isEndClient?: boolean;
    //ReturnCode: number;
}
export class ICompany {
    CompanyID: number;
    Name: string;
    Address1: string;
    Address2: string;
    City: string;
    State: string;
    Country: string;
    ZipCode: string;
    ContactName: string;
    ContactEmail: string;
    ContactPhone: string;
    AlternateContactName: string;
    AlternateContactEmail: string;
    AlternateContactPhone: string;
    InvoiceContactName: string;
    InvoiceContactEmail: string;
    InvoiceContactPhone: string;
    AlternateInvoiceContactName: string;
    AlternateInvoiceContactEmail: string;
    AlternateInvoiceContactPhone: string;
    InvoicingPeriodID: number;
    InvoicingPeriod: string
    PaymentTermID: number;
    PaymentTerm?: string;
    TaxID: number;
    CompanyTypeID?: number;
    CompanyType: string;
    IsEndClient?: boolean;
}
